name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet paket install
    - name: Restore TypeProvider dependencies
      run: dotnet restore "./BioProviders.sln"
    - name: Restore TestAndDocs dependencies
      run: dotnet restore "./BioProviders.TestsAndDocs.sln"
    - name: Build TypeProvider
      run: dotnet build "./BioProviders.sln" --no-restore
    - name: Build TestAndDocs
      run: dotnet build "./BioProviders.TestsAndDocs.sln" --no-restore
    - name: Unit tests
      run: dotnet test "./BioProviders.sln" --no-build --verbosity normal
    - name: TypeProvider tests
      run: dotnet test "./BioProviders.TestsAndDocs.sln" --no-build --verbosity normal
